apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: taxicab-ENVIRONMENT
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java
        version: v1
    spec:
      containers:
      - name: taxicab-ENVIRONMENT
        image: IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
